version: "3.6"

services:
  app:
    build: ./
    container_name: helios_ktor
    volumes:
      - ./:/Helios
    ports:
      - "8081:8081"
    expose:
      - 8081
    depends_on:
      - database
    networks:
      - helios-network
  database:
    container_name: helios_database
    image: postgres:latest
    environment:
      - POSTGRES_DB=helios_database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - helios-network
networks:
  helios-network:
    driver: bridge
